[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/web/Dockerfile"
buildContext = "../../"

[deploy]
startCommand = "/docker-entrypoint.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
